### ISSUE TITLE
Add SimonTest

### ISSUE THREAD

**Issue by KyleBastien** [devboosts/angular-productivity-pack#1]
https://marketplace.visualstudio.com/items?itemName=SimonTest.simontest

Fantastic Extension for creating tests based on a Component that you have.

**Comment by cgatian** [comment]
Wow thanks! I'll take a look at it

**Comment by cgatian** [comment]
Holy crap that looks amazing!

**Comment by cgatian** [comment]
@KyleMcNutt If you don't mind Ill take a look on Monday and actually use it.  Looks great though! This is exactly what I hoped would happen thank you!

**Comment by KyleBastien** [comment]
@cgatian Sounds good!

**Comment by cgatian** [comment]
@KyleMcNutt do you have any others? Perhaps even to evaluate?

**Comment by KyleBastien** [comment]
@cgatian You've captured the majority of my plugins here, the only other one that I use that isn't already captured in your list is Bracket Pair Colorizer:

https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer

But that one is probably not as popular, and also isn't very Angular-specific, I just find it useful for myself.

I also use Untabify:

https://marketplace.visualstudio.com/items?itemName=ilich8086.Untabify

Because my team recently switched from tabs to spaces (thank goodness) and this helps a lot in changing files as you come across old ones that still have tabs. But that is also an extension that is very specific to my workflow.

**Comment by cgatian** [comment]
Oh I use Bracket colorizer too! 👍 👍 👍  I didn't want to force color/themes on people.

Whats the deal with tabs vs. spaces? I thought editorconfig solved that dilemma?

**Comment by cgatian** [comment]
Added in 1.2.0

**Comment by KyleBastien** [comment]
Nice! Thanks Chaz!
