### ISSUE TITLE
Add angular cli support

### ISSUE THREAD

**Issue by gamodg** [devboosts/angular-productivity-pack#10]
You collection is great.
If you could add angular cli to it, it would be awesome

**Comment by cgatian** [comment]
Angular CLI?

**Comment by JThomasTek** [comment]
Not sure what you mean by add Angular CLI since these are VS Code extensions and not NPM node modules. Is there an Angular CLI extension you can recommend?

It makes generation of components, modules, etc. very easy with simple commands: https://github.com/angular/angular-cli

**Comment by gamodg** [comment]
I finally installed https://marketplace.visualstudio.com/items?itemName=web-dave.vsc-angular-cli

I just wanted to add to the awesomeness of the extension pack.

I frequently generate components via angular cli and hence this plugin was the missing piece for me

**Comment by cgatian** [comment]
Thank you I will check out and add!
