### ISSUE TITLE
Property Intellisense not work with "dash"

### ISSUE THREAD

**Issue by ndtien84** [devboosts/angular-productivity-pack#11]
my class is something like this: 

export class PromotionCode {
    
    public PTC_ID: string;
    public PTC_SeqNumber: number;
    public PTC_Type: PromotionCodeType;
    public PTC_ParentsID: string;
    public PTC_CreatedBy: string;
    public PTC_LastUpdatedBy: string;
    public PTC_CreatedDate: Date;
    public PTC_UpdatedDate: Date;
    public PTC_Approved: boolean;
    public PTC_ApprovedDate: Date;
    public PTC_ApplyDate: Date;
    public PTC_StartDate: Date;
    public PTC_ExpiredDate: Date;
    public PTC_IsApplied: boolean;
    public PTC_Prefix: string;
    public PTC_Code: string;
    public PTC_Amount: number;
    public PTC_AmountType: PromotionCodeAmountType;
    public PTC_Name: string;
    public PTC_Note: string;
    public PTC_ApplyNote: string;
    public PTC_AvailableApplyCount: number;
    public PTC_AppliedCount: number;
    
    public IsExpired: boolean;
    public AvailableStatus: PromotionCodeAvailable;
}

The intellisense only work in 2 properties: IsExpired, AvailableStatus. All other properties not work. I think it because the "dash" in the property name.

Can someone help to take a look on this,

Thanks for the awesome product

**Comment by cgatian** [comment]
Sorry this is a vs code extension pack. I think you're reaching out to the wrong repo.

**Comment by ndtien84** [comment]
Sorry, my bad. It should be in the vscode-ng-language-service repo

Thanks,
