### ISSUE TITLE
Angular File Changer

### ISSUE THREAD

**Issue by jtcrowson** [devboosts/angular-productivity-pack#13]
[Marketplace Link](https://marketplace.visualstudio.com/items?itemName=john-crowson.angular-file-changer)

Easy way to switch between angular component files, similar to angular-switcher (already included), but has Touch Bar and NgRx support.

**Comment by cgatian** [comment]
Oh nice! I'll add!

Have you heard of Turbo?
https://marketplace.visualstudio.com/items?itemName=ChakrounAnas.turbo-console-log

**Comment by jtcrowson** [comment]
Hey @cgatian, did Angular File Changer ever get added?

**Comment by cgatian** [comment]
Sorry, just added it!
