### ISSUE TITLE
Add Angular Language Service

### ISSUE THREAD

**Issue by KyleBastien** [devboosts/angular-productivity-pack#6]
https://marketplace.visualstudio.com/items?itemName=Angular.ng-template

**Comment by cgatian** [comment]
Already out in version `1.1.0`

**Comment by cgatian** [comment]
Also @KyleMcNutt Sorry I haven't been able to run the testing snippet yet.

**Comment by KyleBastien** [comment]
Man.. you work fast! Nice! And no problem

**Comment by cgatian** [comment]
@KyleMcNutt yeah I saw it pushed this morning and made a post on reddit, perhaps thats how you saw it?  Anyways, good looking out!
