### ISSUE TITLE
Recommended extension additions

### ISSUE THREAD

**Issue by JThomasTek** [devboosts/angular-productivity-pack#7]
Here are some additions that I feel would be useful in the productivity pack:
* [Auto Close Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag)
* [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer)
* [Cordova Tools](https://marketplace.visualstudio.com/items?itemName=vsmobile.cordova-tools)
* To replace Annotator: [Git Lens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)

**Comment by cgatian** [comment]
For some reason my Git notifications were disabled!  Taking a look. Thank you for the contribution.

**Comment by cgatian** [comment]
Auto Close Tag and Git Lens are awesome! 

I personally use Bracket Pair Colorizer, but don't want to force colors or themes on people.
Cordova is interesting, however I think it isn't specific to Angular

**Comment by cgatian** [comment]
Updated and released in 1.3
